[project]
name = "tg-active-chats-counter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12, <3.13"
dependencies = [
    "cryptg==0.4.0",
    "icecream>=2.1.3",
    "python-dotenv>=1.0.1",
    "telethon==1.36.0",
]
